# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/fake_d/ZedboardPractice/Lab_4/PetaLinux_zynq700/PetaLinux_zynq700.srcs/sources_1/bd/mainProcessingUnit/ip/mainProcessingUnit_auto_pc_0/mainProcessingUnit_auto_pc_0.xci
# IP: The module: 'mainProcessingUnit_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/fake_d/ZedboardPractice/Lab_4/PetaLinux_zynq700/PetaLinux_zynq700.gen/sources_1/bd/mainProcessingUnit/ip/mainProcessingUnit_auto_pc_0/mainProcessingUnit_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mainProcessingUnit_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/fake_d/ZedboardPractice/Lab_4/PetaLinux_zynq700/PetaLinux_zynq700.srcs/sources_1/bd/mainProcessingUnit/ip/mainProcessingUnit_auto_pc_0/mainProcessingUnit_auto_pc_0.xci
# IP: The module: 'mainProcessingUnit_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/fake_d/ZedboardPractice/Lab_4/PetaLinux_zynq700/PetaLinux_zynq700.gen/sources_1/bd/mainProcessingUnit/ip/mainProcessingUnit_auto_pc_0/mainProcessingUnit_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mainProcessingUnit_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
