# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/HardwareConfig1/HardwareConfig1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HardwareConfig1 || ORIG_REF_NAME==HardwareConfig1} -quiet] -quiet

# IP: bd/HardwareConfig1/ip/HardwareConfig1_processing_system7_0_0/HardwareConfig1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HardwareConfig1_processing_system7_0_0 || ORIG_REF_NAME==HardwareConfig1_processing_system7_0_0} -quiet] -quiet

# IP: bd/HardwareConfig1/ip/HardwareConfig1_axi_gpio_0_0/HardwareConfig1_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HardwareConfig1_axi_gpio_0_0 || ORIG_REF_NAME==HardwareConfig1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/HardwareConfig1/ip/HardwareConfig1_ps7_0_axi_periph_0/HardwareConfig1_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HardwareConfig1_ps7_0_axi_periph_0 || ORIG_REF_NAME==HardwareConfig1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/HardwareConfig1/ip/HardwareConfig1_rst_ps7_0_100M_0/HardwareConfig1_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HardwareConfig1_rst_ps7_0_100M_0 || ORIG_REF_NAME==HardwareConfig1_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/HardwareConfig1/ip/HardwareConfig1_auto_pc_0/HardwareConfig1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HardwareConfig1_auto_pc_0 || ORIG_REF_NAME==HardwareConfig1_auto_pc_0} -quiet] -quiet

# XDC: c:/fake_d/ZedboardPractice/PetalinuxTest/Zynq_hardware/Zynq_hardware.gen/sources_1/bd/HardwareConfig1/HardwareConfig1_ooc.xdc
