# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/mainProcessingUnit/mainProcessingUnit.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mainProcessingUnit || ORIG_REF_NAME==mainProcessingUnit} -quiet] -quiet

# IP: bd/mainProcessingUnit/ip/mainProcessingUnit_processing_system7_0_0/mainProcessingUnit_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mainProcessingUnit_processing_system7_0_0 || ORIG_REF_NAME==mainProcessingUnit_processing_system7_0_0} -quiet] -quiet

# IP: bd/mainProcessingUnit/ip/mainProcessingUnit_axi_gpio_0_0/mainProcessingUnit_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mainProcessingUnit_axi_gpio_0_0 || ORIG_REF_NAME==mainProcessingUnit_axi_gpio_0_0} -quiet] -quiet

# IP: bd/mainProcessingUnit/ip/mainProcessingUnit_auto_pc_0/mainProcessingUnit_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mainProcessingUnit_auto_pc_0 || ORIG_REF_NAME==mainProcessingUnit_auto_pc_0} -quiet] -quiet

# IP: bd/mainProcessingUnit/ip/mainProcessingUnit_ps7_0_axi_periph_0/mainProcessingUnit_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mainProcessingUnit_ps7_0_axi_periph_0 || ORIG_REF_NAME==mainProcessingUnit_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/mainProcessingUnit/ip/mainProcessingUnit_rst_ps7_0_100M_0/mainProcessingUnit_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mainProcessingUnit_rst_ps7_0_100M_0 || ORIG_REF_NAME==mainProcessingUnit_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: c:/fake_d/ZedboardPractice/Lab_4/PetaLinux_zynq700/PetaLinux_zynq700.gen/sources_1/bd/mainProcessingUnit/mainProcessingUnit_ooc.xdc
