# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/fake_d/ZedboardPractice/PetalinuxTest/Zynq_hardware/Zynq_hardware.srcs/sources_1/bd/HardwareConfig1/ip/HardwareConfig1_axi_gpio_0_0/HardwareConfig1_axi_gpio_0_0.xci
# IP: The module: 'HardwareConfig1_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/fake_d/ZedboardPractice/PetalinuxTest/Zynq_hardware/Zynq_hardware.gen/sources_1/bd/HardwareConfig1/ip/HardwareConfig1_axi_gpio_0_0/HardwareConfig1_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'HardwareConfig1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/fake_d/ZedboardPractice/PetalinuxTest/Zynq_hardware/Zynq_hardware.gen/sources_1/bd/HardwareConfig1/ip/HardwareConfig1_axi_gpio_0_0/HardwareConfig1_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'HardwareConfig1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/fake_d/ZedboardPractice/PetalinuxTest/Zynq_hardware/Zynq_hardware.gen/sources_1/bd/HardwareConfig1/ip/HardwareConfig1_axi_gpio_0_0/HardwareConfig1_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'HardwareConfig1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/fake_d/ZedboardPractice/PetalinuxTest/Zynq_hardware/Zynq_hardware.srcs/sources_1/bd/HardwareConfig1/ip/HardwareConfig1_axi_gpio_0_0/HardwareConfig1_axi_gpio_0_0.xci
# IP: The module: 'HardwareConfig1_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/fake_d/ZedboardPractice/PetalinuxTest/Zynq_hardware/Zynq_hardware.gen/sources_1/bd/HardwareConfig1/ip/HardwareConfig1_axi_gpio_0_0/HardwareConfig1_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'HardwareConfig1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/fake_d/ZedboardPractice/PetalinuxTest/Zynq_hardware/Zynq_hardware.gen/sources_1/bd/HardwareConfig1/ip/HardwareConfig1_axi_gpio_0_0/HardwareConfig1_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'HardwareConfig1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/fake_d/ZedboardPractice/PetalinuxTest/Zynq_hardware/Zynq_hardware.gen/sources_1/bd/HardwareConfig1/ip/HardwareConfig1_axi_gpio_0_0/HardwareConfig1_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'HardwareConfig1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
